### ISSUE TITLE
outer image and graphic map

### ISSUE THREAD

**Issue by blefort** [dita4publishers/org.dita4publishers.common.xslt#2]
The graphic map does seems not support ‘outer’ images. I mean that if an image is in a sibling directory than the ditamap parent directory, the resolved path is wrong.

I found in the generated list that up levels is a property available that seems to provide the ‘real’ parent directory information. The path in the image.list seems show path related to this parent directory.

_An example_

Map

```
fr-ca/system/map.ditamap
```

Images located in

```
en-ca/system/assets/images/image.jpg
```

the final path is resolved to 

```
fr-ca/system/fr-ca/system/assets/images/image.jpg
```

The image.list provides this information, when resolving an image

```
en-ca/system/assets/images/image.jpg
```

I found this ant property `uplevels`, also available in dita.list which seems to provide the missing information, which is in this case:
`uplevels = ../../`

I am not sure if I can use it.

What do you think about this ?

**Comment by paperdigits** [comment]
Is that with the generate outer copy option set to 3?

**Comment by blefort** [comment]
Yes. I tried both outer.control and generate.copy.outer and it does not change the behaviour.
The pdf transtype handle the reference properly.

@drmacro : I can help on this one, just want to confirm the approach first.

**Comment by blefort** [comment]
I proposed a patch in a separated branch. It requires to update all transform to pass the additional param and to pass the ant property to the xsl.

``` xml
<xsl:apply-templates select="." mode="generate-graphic-map">
  <xsl:with-param name="uplevels" select="$uplevels" as="xs:string" tunnel="yes" />
</xsl:apply-templates>
```

**Comment by drmacro** [comment]
That seems like a reasonable solution.
